ARG BUN_IMAGE
ARG NODE_IMAGE

FROM ${BUN_IMAGE} AS bun
WORKDIR /app

FROM bun AS prune
ARG APP
ARG BUN_IMAGE
ARG NODE_IMAGE
ENV CI=1 TURBO_TELEMETRY_DISABLED=1
COPY . .
RUN case "$BUN_IMAGE" in *@sha256:*) ;; *) exit 1 ;; esac && \
    case "$NODE_IMAGE" in *@sha256:*) ;; *) exit 1 ;; esac && \
    case "$APP" in api|web|docs) ;; *) exit 1 ;; esac && \
    bun -e 'const p=await Bun.file("package.json").json(); if(p.packageManager!==`bun@${Bun.version}` || p.devDependencies.turbo!=="2.10.9") throw Error("Build tooling must match the source lock");' && \
    bunx --bun turbo@2.10.9 prune "@superset/$APP" --docker

FROM ${NODE_IMAGE} AS node

FROM node AS builder
COPY --from=bun /usr/local/bin/bun /usr/local/bin/bun
WORKDIR /app
ENV CI=1 NEXT_TELEMETRY_DISABLED=1 TURBO_TELEMETRY_DISABLED=1
COPY --from=prune /app/out/json/ ./
COPY patches/ ./patches/
RUN node -e 'if(process.versions.node.split(".")[0]!=="24") throw Error("Node 24 is required");' && \
    bun install --frozen-lockfile --ignore-scripts
COPY --from=prune /app/out/full/ ./
COPY lingui.config.ts ./lingui.config.ts
COPY docker/self-host/next-build.sh /usr/local/bin/next-build

ARG APP
ARG APPLE_TEAM_ID
ARG EXPO_PUBLIC_IOS_BUNDLE_ID
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_WEB_URL
ARG NEXT_PUBLIC_ADMIN_URL
ARG NEXT_PUBLIC_MARKETING_URL
ARG NEXT_PUBLIC_DOCS_URL
ARG NEXT_PUBLIC_DOWNLOAD_URL
ARG NEXT_PUBLIC_DESKTOP_URL
ARG NEXT_PUBLIC_ROOT_DOMAIN
ARG NEXT_PUBLIC_RELAY_URL
ARG NEXT_PUBLIC_REALTIME_URL
ARG NEXT_PUBLIC_AUTH_PROVIDERS
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_POSTHOG_HOST
ARG NEXT_PUBLIC_SENTRY_DSN_API
ARG NEXT_PUBLIC_SENTRY_DSN_WEB
ARG NEXT_PUBLIC_SENTRY_DSN_DOCS
ARG NEXT_PUBLIC_SENTRY_ENVIRONMENT
ARG RELAY_URL
ARG RELAY_BACKUP_URL
ARG REALTIME_URL
ARG USERCONTENT_URL
ENV APPLE_TEAM_ID=$APPLE_TEAM_ID EXPO_PUBLIC_IOS_BUNDLE_ID=$EXPO_PUBLIC_IOS_BUNDLE_ID \
    NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_WEB_URL=$NEXT_PUBLIC_WEB_URL \
    NEXT_PUBLIC_ADMIN_URL=$NEXT_PUBLIC_ADMIN_URL \
    NEXT_PUBLIC_MARKETING_URL=$NEXT_PUBLIC_MARKETING_URL \
    NEXT_PUBLIC_DOCS_URL=$NEXT_PUBLIC_DOCS_URL \
    NEXT_PUBLIC_DOWNLOAD_URL=$NEXT_PUBLIC_DOWNLOAD_URL \
    NEXT_PUBLIC_DESKTOP_URL=$NEXT_PUBLIC_DESKTOP_URL \
    NEXT_PUBLIC_ROOT_DOMAIN=$NEXT_PUBLIC_ROOT_DOMAIN \
    NEXT_PUBLIC_RELAY_URL=$NEXT_PUBLIC_RELAY_URL \
    NEXT_PUBLIC_REALTIME_URL=$NEXT_PUBLIC_REALTIME_URL \
    NEXT_PUBLIC_AUTH_PROVIDERS=$NEXT_PUBLIC_AUTH_PROVIDERS \
    NEXT_PUBLIC_POSTHOG_KEY=$NEXT_PUBLIC_POSTHOG_KEY \
    NEXT_PUBLIC_POSTHOG_HOST=$NEXT_PUBLIC_POSTHOG_HOST \
    NEXT_PUBLIC_SENTRY_DSN_API=$NEXT_PUBLIC_SENTRY_DSN_API \
    NEXT_PUBLIC_SENTRY_DSN_WEB=$NEXT_PUBLIC_SENTRY_DSN_WEB \
    NEXT_PUBLIC_SENTRY_DSN_DOCS=$NEXT_PUBLIC_SENTRY_DSN_DOCS \
    NEXT_PUBLIC_SENTRY_ENVIRONMENT=$NEXT_PUBLIC_SENTRY_ENVIRONMENT \
    RELAY_URL=$RELAY_URL RELAY_BACKUP_URL=$RELAY_BACKUP_URL \
    REALTIME_URL=$REALTIME_URL USERCONTENT_URL=$USERCONTENT_URL
RUN /bin/sh /usr/local/bin/next-build "$APP" /app /release

FROM node AS runner
ARG APP
WORKDIR /app/apps/${APP}
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 HOSTNAME=0.0.0.0 PORT=3000
COPY --from=builder --chown=node:node /release/ /app/
USER node
EXPOSE 3000
CMD ["node", "server.js"]
